# Generated by Django 4.2.4 on 2023-08-19 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicaciones', '0004_folder_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tspeaker_trans',
            name='uploaded_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='Aplicaciones.uploadedfile'),
        ),
    ]
